### ISSUE TITLE
Index error on last batch with shuffle set to False

### ISSUE THREAD

**Issue by samzoozi** [Britefury/batchup#19]
I wanted to report an issue which seems to be a bug to me. Whenever I create a batch_iterator over my dataset with shuffle set to False, I am getting an index error just after reading the last batch like this:

> index 8017 is out of bounds for axis 0 with size 801

This does not happen when shuffle is set to True. In this case the last batch is smaller in size as noted in the documentation.

**Comment by Britefury** [comment]
Are you using a CompositeDataSource? If so it might have been fixed.
If not, could you provide a little example code to highlight the issue?

**Comment by samzoozi** [comment]
Thanks for reply. No I was using ArrayDataSource.
Here is an example: 
`ds = data_source.ArrayDataSource([x_train, y_train])
for (batch_xs, batch_ys) in ds.batch_iterator(batch_size=64,shuffle=False):
    print(batch_xs.shape)`
When I read from batch_iterator with shuffle set to True there is no issue and the last batch is smaller in size, but when shuffle is set to False I get this error:

> IndexError: index 8017 is out of bounds for axis 0 with size 8017
8017 is size of my data. Don't who why it needs to access that.  Maybe I am doing something wrong? Here is the detailed traceback:

> IndexError                                Traceback (most recent call last)
<ipython-input-35-5f02abad1ed1> in <module>()
      1 ds = data_source.ArrayDataSource([x_train, y_train])
----> 2 for (batch_xs, batch_ys) in ds.batch_iterator(batch_size=batch_size,shuffle=False):
      3     print(batch_xs.shape)

/home/samzoozi/.local/lib/python3.6/site-packages/batchup/data_source.py in batch_iterator(self, batch_size, shuffle, **kwargs)
    669         for batch_ndx in self.batch_indices_iterator(
    670                 batch_size, shuffle=shuffle, **kwargs):
--> 671             yield self.samples_by_indices_nomapping(batch_ndx)
    672 
    673 

/home/samzoozi/.local/lib/python3.6/site-packages/batchup/data_source.py in samples_by_indices_nomapping(self, indices)
    820             A mini-batch in the form of a list of NumPy arrays
    821         """
--> 822         batch = tuple([d[indices] for d in self.data])
    823         if self.include_indices:
    824             if isinstance(indices, slice):

/home/samzoozi/.local/lib/python3.6/site-packages/batchup/data_source.py in <listcomp>(.0)
    820             A mini-batch in the form of a list of NumPy arrays
    821         """
--> 822         batch = tuple([d[indices] for d in self.data])
    823         if self.include_indices:
    824             if isinstance(indices, slice):

IndexError: index 8017 is out of bounds for axis 0 with size 8017

**Comment by Britefury** [comment]
Hmmm....

The following code seems to run fine:

```py3
import numpy as np
from batchup import data_source

x_train = np.random.normal(size=(8017,10))
y_train = np.random.randint(0, 10, size=(8017,))

ds = data_source.ArrayDataSource([x_train, y_train])
for bx, by in ds.batch_iterator(batch_size=64, shuffle=False):
	print(bx.shape)
```

What types are `train_x` and `train_y` in your code? Regular NumPy arrays?

**Comment by samzoozi** [comment]
Ok I guess the issue was for the older version that I had installed. I upgraded the library and the issue is resolved.  
Thanks for the support :+1:

**Comment by Britefury** [comment]
Cool, thanks for letting me know.
